### ISSUE TITLE
Figure out space and CPU requirements

### ISSUE THREAD

**Issue by hajicj** [kukas/melody_extraction#1]
In order to ask for a VM, we need to tell our IT dept how much space and processing power we need.

* CPU
* RAM
* Disk space

Measure CPU requirements locally, on both short (~20 s) and long (~4 min) excerpts. Send model of processor and approx. computing power, and CPU load percentages.

**Comment by kukas** [comment]
Complete table of measured values for CPU and RAM usage can be found [here](https://docs.google.com/spreadsheets/d/1qwdI1eGLOcP9Mu-fAwYq6nXSBSaj4XuGnPX_Ndaxr-A/edit#gid=659898430)

The most computationally expensive algorithm requires:
RAM: 550mb per 20 seconds of audio
CPU: 3 minutes of CPU time (4 threads, Intel Core i5 520M)

**Comment by kukas** [comment]
As for the disk space, my collection of datasets takes 2gb, Orchset takes 360mb. So anything between these values seems reasonable to me.
