### ISSUE TITLE
Figure out dependencies for algorithms

### ISSUE THREAD

**Issue by hajicj** [kukas/melody_extraction#5]
For each algorithm, we need to know:

* What Python?
* What Python packages? Versions (numpy, scipy, theano, tensorflow...)?
* What other dependencies?

**Comment by hajicj** [comment]
Also figure out dependencies for the server, in order to gauge potential conflicts between the server and the virtual environments.

**Comment by kukas** [comment]
Dependencies are resolved by running the install script. Requirements lists for each algorithm can be found in this commit: ee61439b58686d74c6f12d8c9d187c56c4b59ab3
